description: |
  Use one of our pre-included templates for sending a success notification when a tagged deployment passes.
  Ensure the "msteams/notify" command is the last command in a job to accurately capture the status.
usage:
  version: 2.1
  orbs:
    msteams: munibillingllc/msteams-circleci-orb@0.1.14
    node: circleci/node:4.1
  jobs:
    deploy:
      executor:
        name: node/default
      steps:
        - checkout
        - node/install-packages
        - run:
            command: npm run deploy
        - msteams/notify:
            event: pass
            template: success_tagged_deploy_1
  workflows:
    deploy_and_notify:
      jobs:
        - deploy:
            context:
              - msteams-secrets
